trees:
  - path: /
    tree: aimmdb.adapters.aimm:AIMMCatalog.from_uri
    #    tree: aimmdb.adapters.mongo:MongoAdapter.from_uri
    args:
      uri: mongodb://root:${MONGO_PASSWORD}@localhost:27018/aimm?authSource=admin
      data_directory: ./data
      dataset_to_specs:
        nmc:
          - XAS_TFY
          - XAS_TEY
          - XAS_trans
    access_control:
      access_policy: aimmdb.access:DatasetAccessPolicy
      args:
        provider: toy
        access_lists:
          joe:
            default: rw
          dan:
            default: r
authentication:
  allow_anonymous_access: false
  providers:
    - provider: toy
      authenticator: tiled.authenticators:DictionaryAuthenticator
      args:
        users_to_passwords:
          joe: abc123
          dan: abc123
  tiled_admins:
    - provider: toy
      id: joe
validation:
  XAS_TFY: aimmdb.validation:validate_xas_tfy
  XAS_TEY: aimmdb.validation:validate_xas_tey
  XAS_trans: aimmdb.validation:validate_xas_transmission
